services:
  app:
    build: ./app
#    depends_on:
#      - db
  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
