version: "3"
services:
  app:
    build: ./app
#    depends_on:
#      - db
  db:
    image: postgres:17.5-alpine
    environment:
      - POSTGRES_PASSWORD=petproject_pass
      - POSTGRES_USER=sql_admin
      - POSTGRES_DB=request
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
